### ISSUE TITLE
終了時にpanicを起こす

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/MusicalTyper-Go#7]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x40ca0d6]

goroutine 1 [running, locked to thread]:
MusicalTyper-Go/Game/Beatmap.(*Sentence).GetTypedText(...)
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Game/Beatmap/Sentence.go:41
MusicalTyper-Go/Game/DrawComponents/MainArea.TypeText.Draw(0xc000070660)
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Game/DrawComponents/MainArea/TypeText.go:27 +0x66
MusicalTyper-Go/Game/DrawComponents/DrawManager.drawEffectors(0xc000070660, 0x4219620, 0x8, 0x8, 0x42464b8, 0x0, 0x0, 0x42464b8, 0x0, 0x0)
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Game/DrawComponents/DrawManager/Draw.go:68 +0x71
MusicalTyper-Go/Game/DrawComponents/DrawManager.Draw(0xc000070660)
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Game/DrawComponents/DrawManager/Draw.go:48 +0xfe
MusicalTyper-Go/Game.Run.func1()
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Game/Game.go:116 +0x76e
github.com/veandco/go-sdl2/sdl.Main.func1.1()
	/Users/misato/dev/go/pkg/mod/github.com/veandco/go-sdl2@v0.4.1/sdl/sdl.go:86 +0x2f
github.com/veandco/go-sdl2/sdl.Main(0xc000209d50)
	/Users/misato/dev/go/pkg/mod/github.com/veandco/go-sdl2@v0.4.1/sdl/sdl.go:99 +0xc1
main.main()
	/Users/misato/dev/go/src/github.com/brokenManager/MusicalTyper-Go/Main.go:31 +0x65
```

**Comment by kawaemon** [comment]
リザルドスクリーン実装時に修正します。

**Comment by mirror-kt** [comment]
リザルトスクリーン: #4

**Comment by kawaemon** [comment]
eadf37dc99597d65b0fef17b6b8efca82e35d490
で修正
